"""Initial migration for user_info table

Revision ID: 09eb325dbb12
Revises:
Create Date: 2025-07-25 15:23:58.997554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09eb325dbb12'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.String(length=255), nullable=False),
        sa.Column('timestamp', sa.BigInteger(), nullable=False),
        sa.Column('x', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('y', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('z', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('floor', sa.Integer(), nullable=False),
        sa.Column('device_name', sa.String(length=255), nullable=False),
        sa.Column('sensor_status', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_info')
    # ### end Alembic commands ###
